title: Desenhando com Mack
email: your-email@example.com
description: Este é o site oficial do canal Desenhando com Mack
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://desenhandocommack.com.br"

social:
  - twitter: mackdesenhos
  - facebook: desenhandocommack
  - youtube: desenhandocommack
  - instagram: desenhandocommack

author:
  - name: Mack
  - avatar: https://placeimg.com/50/50/people

paginate: 6
paginate_path: "/blog/page-:num/"
permalink: /blog/:title/

meu_map:
 - title: "Início"
   url: "/"
 - title: "O Projeto"
   url: "o-projeto"
 - title: "Blog"
   url: "blog"
 - title: "Now"
   url: "now"
 - title: "Contato"
   url: "contato"

plugins:
  - jekyll-paginate
  - jekyll-octicons

sass:
    style: compressed

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: post
