markdown:         redcarpet
highlighter:      pygments

permalink:        pretty

title:            Desenhando com Mack
url:              http://desenhandocommack.com.br
baseurl:          /
author:
  name:           Mack
  url:            https://twitter.com/mackdesenhos
github:           [metadata]
