baseURL = 'https://desenhandocommack.github.io/'
languageCode = 'pt-br'
title = 'Desenhando com Mack'
theme = 'custom'
[permalinks]
blog = ':slug'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
